//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-520 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.08.14 at 04:03:17 PM IST 
//

package pcs.pradeep.dubey.com.project;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

import pcs.pradeep.dubey.com.baseentity.AddressDetails;

/**
 * <p>
 * Java class for Project complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name="Project">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="id" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="description" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="workflowList" type="{http:/com.dubey.pradeep.pcs/Project}WorkFlowList"/>
 *         &lt;element name="addressOfProject" type="{http:/com.dubey.pradeep.pcs/baseEntity}AddressDetails"/>
 *         &lt;element name="status" type="{http:/com.dubey.pradeep.pcs/Project}ProjectStatus"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlRootElement(name = "Project")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Project", propOrder = { "id", "description", "workflowList", "addressOfProject", "status" })
public class Project {

    @XmlElement(required = true)
    protected String id;
    @XmlElement(required = true)
    protected String description;
    @XmlElement(required = true)
    protected WorkFlowList workflowList;
    @XmlElement(required = true)
    protected AddressDetails addressOfProject;
    @XmlElement(required = true)
    protected ProjectStatus status;

    /**
     * Gets the value of the id property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getId() {
	return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setId(String value) {
	this.id = value;
    }

    /**
     * Gets the value of the description property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getDescription() {
	return description;
    }

    /**
     * Sets the value of the description property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setDescription(String value) {
	this.description = value;
    }

    /**
     * Gets the value of the workflowList property.
     * 
     * @return possible object is {@link WorkFlowList }
     * 
     */
    public WorkFlowList getWorkflowList() {
	return workflowList;
    }

    /**
     * Sets the value of the workflowList property.
     * 
     * @param value
     *            allowed object is {@link WorkFlowList }
     * 
     */
    public void setWorkflowList(WorkFlowList value) {
	this.workflowList = value;
    }

    /**
     * Gets the value of the addressOfProject property.
     * 
     * @return possible object is {@link AddressDetails }
     * 
     */
    public AddressDetails getAddressOfProject() {
	return addressOfProject;
    }

    /**
     * Sets the value of the addressOfProject property.
     * 
     * @param value
     *            allowed object is {@link AddressDetails }
     * 
     */
    public void setAddressOfProject(AddressDetails value) {
	this.addressOfProject = value;
    }

    /**
     * Gets the value of the status property.
     * 
     * @return possible object is {@link ProjectStatus }
     * 
     */
    public ProjectStatus getStatus() {
	return status;
    }

    /**
     * Sets the value of the status property.
     * 
     * @param value
     *            allowed object is {@link ProjectStatus }
     * 
     */
    public void setStatus(ProjectStatus value) {
	this.status = value;
    }

}
