//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-520 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.08.14 at 04:03:17 PM IST 
//


package pcs.pradeep.dubey.com.project;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import pcs.pradeep.dubey.com.baseentity.WorkFlow;


/**
 * <p>Java class for WorkFlowList complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="WorkFlowList">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="flowList" type="{http:/com.dubey.pradeep.pcs/baseEntity}WorkFlow" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "WorkFlowList", propOrder = {
    "flowList"
})
public class WorkFlowList {

    @XmlElement(required = true)
    protected List<WorkFlow> flowList;

    /**
     * Gets the value of the flowList property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the flowList property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getFlowList().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link WorkFlow }
     * 
     * 
     */
    public List<WorkFlow> getFlowList() {
        if (flowList == null) {
            flowList = new ArrayList<WorkFlow>();
        }
        return this.flowList;
    }

}
