//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-520 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.08.17 at 11:23:24 AM IST 
//


package pcs.pradeep.dubey.com.employee;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Designation.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="Designation">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="Admin"/>
 *     &lt;enumeration value="Approver"/>
 *     &lt;enumeration value="Designer"/>
 *     &lt;enumeration value="Field Engineer"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "Designation")
@XmlEnum
public enum Designation {

    @XmlEnumValue("Admin")
    ADMIN("Admin"),
    @XmlEnumValue("Approver")
    APPROVER("Approver"),
    @XmlEnumValue("Designer")
    DESIGNER("Designer"),
    @XmlEnumValue("Field Engineer")
    FIELD_ENGINEER("Field Engineer");
    private final String value;

    Designation(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static Designation fromValue(String v) {
        for (Designation c: Designation.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
