//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-520 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.08.14 at 04:03:17 PM IST 
//

package pcs.pradeep.dubey.com.employee;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;

import pcs.pradeep.dubey.com.baseentity.AddressDetails;
import pcs.pradeep.dubey.com.baseentity.CommunicationDetails;
import pcs.pradeep.dubey.com.baseentity.PersonalDetails;

/**
 * <p>
 * Java class for Employee complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name="Employee">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="empId" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="dateOfJoining" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *         &lt;element name="designation" type="{http:/com.dubey.pradeep.pcs/Employee}Designation"/>
 *         &lt;element name="addressDetails" type="{http:/com.dubey.pradeep.pcs/baseEntity}AddressDetails"/>
 *         &lt;element name="communicationDetails" type="{http:/com.dubey.pradeep.pcs/baseEntity}CommunicationDetails"/>
 *         &lt;element name="personalDetails" type="{http:/com.dubey.pradeep.pcs/baseEntity}PersonalDetails"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlRootElement(name = "Employee")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Employee", propOrder = { "empId", "dateOfJoining", "designation", "addressDetails",
	"communicationDetails", "personalDetails" })
public class Employee {

    @XmlElement(required = true)
    protected String empId;
    @XmlElement(required = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar dateOfJoining;
    @XmlElement(required = true)
    protected Designation designation;
    @XmlElement(required = true)
    protected AddressDetails addressDetails;
    @XmlElement(required = true)
    protected CommunicationDetails communicationDetails;
    @XmlElement(required = true)
    protected PersonalDetails personalDetails;

    /**
     * Gets the value of the empId property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getEmpId() {
	return empId;
    }

    /**
     * Sets the value of the empId property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setEmpId(String value) {
	this.empId = value;
    }

    /**
     * Gets the value of the dateOfJoining property.
     * 
     * @return possible object is {@link XMLGregorianCalendar }
     * 
     */
    public XMLGregorianCalendar getDateOfJoining() {
	return dateOfJoining;
    }

    /**
     * Sets the value of the dateOfJoining property.
     * 
     * @param value
     *            allowed object is {@link XMLGregorianCalendar }
     * 
     */
    public void setDateOfJoining(XMLGregorianCalendar value) {
	this.dateOfJoining = value;
    }

    /**
     * Gets the value of the designation property.
     * 
     * @return possible object is {@link Designation }
     * 
     */
    public Designation getDesignation() {
	return designation;
    }

    /**
     * Sets the value of the designation property.
     * 
     * @param value
     *            allowed object is {@link Designation }
     * 
     */
    public void setDesignation(Designation value) {
	this.designation = value;
    }

    /**
     * Gets the value of the addressDetails property.
     * 
     * @return possible object is {@link AddressDetails }
     * 
     */
    public AddressDetails getAddressDetails() {
	return addressDetails;
    }

    /**
     * Sets the value of the addressDetails property.
     * 
     * @param value
     *            allowed object is {@link AddressDetails }
     * 
     */
    public void setAddressDetails(AddressDetails value) {
	this.addressDetails = value;
    }

    /**
     * Gets the value of the communicationDetails property.
     * 
     * @return possible object is {@link CommunicationDetails }
     * 
     */
    public CommunicationDetails getCommunicationDetails() {
	return communicationDetails;
    }

    /**
     * Sets the value of the communicationDetails property.
     * 
     * @param value
     *            allowed object is {@link CommunicationDetails }
     * 
     */
    public void setCommunicationDetails(CommunicationDetails value) {
	this.communicationDetails = value;
    }

    /**
     * Gets the value of the personalDetails property.
     * 
     * @return possible object is {@link PersonalDetails }
     * 
     */
    public PersonalDetails getPersonalDetails() {
	return personalDetails;
    }

    /**
     * Sets the value of the personalDetails property.
     * 
     * @param value
     *            allowed object is {@link PersonalDetails }
     * 
     */
    public void setPersonalDetails(PersonalDetails value) {
	this.personalDetails = value;
    }

}
