//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-520 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.08.17 at 11:23:24 AM IST 
//

package pcs.pradeep.dubey.com.employee;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;

import pcs.pradeep.dubey.com.customer.CustomerList;

/**
 * This object contains factory methods for each Java content interface and Java
 * element interface generated in the pcs.pradeep.dubey.com.employee package.
 * <p>
 * An ObjectFactory allows you to programatically construct new instances of the
 * Java representation for XML content. The Java representation of XML content
 * can consist of schema derived interfaces and classes representing the binding
 * of schema type definitions, element declarations and model groups. Factory
 * methods for each of these are provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Employee_QNAME = new QName("http:/com.dubey.pradeep.pcs/Employee", "Employee");

    /**
     * Create a new ObjectFactory that can be used to create new instances of
     * schema derived classes for package: pcs.pradeep.dubey.com.employee
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link CustomerList }
     * 
     */
    public EmployeeList createEmployeeList() {
	return new EmployeeList();
    }

    /**
     * Create an instance of {@link Employee }
     * 
     */
    public Employee createEmployee() {
	return new Employee();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Employee
     * }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http:/com.dubey.pradeep.pcs/Employee", name = "Employee")
    public JAXBElement<Employee> createEmployee(Employee value) {
	return new JAXBElement<Employee>(_Employee_QNAME, Employee.class, null, value);
    }

}
