//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-520 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.08.14 at 04:03:17 PM IST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http:/com.dubey.pradeep.pcs/Employee")
package pcs.pradeep.dubey.com.employee;
