/**
 * 
 */
package pcs.pradeep.dubey.com.service.utils;

/**
 * This file contains relative location on the server where all the files must
 * be persisted
 * 
 * During back up also this file location used
 * 
 * @author prdubey
 *
 */
public class DataFileFolderLocations {
    public static final String FILE_EXTENSION = ".xml";

    enum Service {
	INSTANCE;

	/** Environment Variable must be declared at OS level */
	String APACHE_CONTAINER_HOME = "CATALINA_HOME";

	/**
	 * Server Root location where are data stored generated by application
	 * itself
	 */
	String USER_DATA_PATH;

	/** Server Location to Store Employee Data */
	String EMPLOYEE_RELATIVE_PATH;

	/** Server Location to Store Customer Data */
	String CUSTOMER_RELATIVE_PATH;

	/** Server Location to Store Project Data */
	String PROJECT_RELATIVE_PATH;

	private Service() {
	    // This folder and its subsequent child folder must be created at
	    // Server
	    USER_DATA_PATH = System.getenv(APACHE_CONTAINER_HOME) + "//userData";
	    EMPLOYEE_RELATIVE_PATH = USER_DATA_PATH + "\\employee\\";
	    CUSTOMER_RELATIVE_PATH = USER_DATA_PATH + "\\customer\\";
	    PROJECT_RELATIVE_PATH = USER_DATA_PATH + "\\project\\";
	}
    }

    public static String getUserDataPath() {
	return Service.INSTANCE.USER_DATA_PATH;
    }

    public static String getEmployeeDataPath() {
	return Service.INSTANCE.EMPLOYEE_RELATIVE_PATH;
    }

    public static String getCustomerDataPath() {
	return Service.INSTANCE.CUSTOMER_RELATIVE_PATH;
    }

    public static String getProjectPath() {
	return Service.INSTANCE.PROJECT_RELATIVE_PATH;
    }
}
