//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-520 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.08.25 at 08:13:02 PM IST 
//


package pcs.pradeep.dubey.com.baseentity;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the pcs.pradeep.dubey.com.baseentity package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: pcs.pradeep.dubey.com.baseentity
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link TaskComment }
     * 
     */
    public TaskComment createTaskComment() {
        return new TaskComment();
    }

    /**
     * Create an instance of {@link TaskArtifacts }
     * 
     */
    public TaskArtifacts createTaskArtifacts() {
        return new TaskArtifacts();
    }

    /**
     * Create an instance of {@link CommunicationDetails }
     * 
     */
    public CommunicationDetails createCommunicationDetails() {
        return new CommunicationDetails();
    }

    /**
     * Create an instance of {@link Task }
     * 
     */
    public Task createTask() {
        return new Task();
    }

    /**
     * Create an instance of {@link PersonalDetails }
     * 
     */
    public PersonalDetails createPersonalDetails() {
        return new PersonalDetails();
    }

    /**
     * Create an instance of {@link TaskAssignementDetails }
     * 
     */
    public TaskAssignementDetails createTaskAssignementDetails() {
        return new TaskAssignementDetails();
    }

    /**
     * Create an instance of {@link AddressDetails }
     * 
     */
    public AddressDetails createAddressDetails() {
        return new AddressDetails();
    }

    /**
     * Create an instance of {@link WorkFlow }
     * 
     */
    public WorkFlow createWorkFlow() {
        return new WorkFlow();
    }

}
