//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-520 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.08.25 at 08:13:02 PM IST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http:/com.dubey.pradeep.pcs/baseEntity")
package pcs.pradeep.dubey.com.baseentity;
