//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-520 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.08.19 at 12:28:13 PM IST 
//


package pcs.pradeep.dubey.com.baseentity;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Task complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Task">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="taskId" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="parentTaskId" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="orderOfExecution" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="taskComment" type="{http:/com.dubey.pradeep.pcs/baseEntity}TaskComment" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="artifacts" type="{http:/com.dubey.pradeep.pcs/baseEntity}TaskArtifacts" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="assignmentDetails" type="{http:/com.dubey.pradeep.pcs/baseEntity}TaskAssignementDetails"/>
 *         &lt;element name="subTaskList" type="{http:/com.dubey.pradeep.pcs/baseEntity}Task" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="taskStatus" type="{http:/com.dubey.pradeep.pcs/baseEntity}TaskStatus"/>
 *         &lt;element name="notes" type="{http:/com.dubey.pradeep.pcs/baseEntity}TaskComment"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Task", propOrder = {
    "taskId",
    "parentTaskId",
    "orderOfExecution",
    "taskComment",
    "artifacts",
    "assignmentDetails",
    "subTaskList",
    "taskStatus",
    "notes"
})
public class Task {

    @XmlElement(required = true)
    protected String taskId;
    @XmlElement(required = true)
    protected String parentTaskId;
    protected int orderOfExecution;
    protected List<TaskComment> taskComment;
    protected List<TaskArtifacts> artifacts;
    @XmlElement(required = true)
    protected TaskAssignementDetails assignmentDetails;
    protected List<Task> subTaskList;
    @XmlElement(required = true)
    protected TaskStatus taskStatus;
    @XmlElement(required = true)
    protected TaskComment notes;

    /**
     * Gets the value of the taskId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTaskId() {
        return taskId;
    }

    /**
     * Sets the value of the taskId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTaskId(String value) {
        this.taskId = value;
    }

    /**
     * Gets the value of the parentTaskId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getParentTaskId() {
        return parentTaskId;
    }

    /**
     * Sets the value of the parentTaskId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setParentTaskId(String value) {
        this.parentTaskId = value;
    }

    /**
     * Gets the value of the orderOfExecution property.
     * 
     */
    public int getOrderOfExecution() {
        return orderOfExecution;
    }

    /**
     * Sets the value of the orderOfExecution property.
     * 
     */
    public void setOrderOfExecution(int value) {
        this.orderOfExecution = value;
    }

    /**
     * Gets the value of the taskComment property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the taskComment property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTaskComment().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TaskComment }
     * 
     * 
     */
    public List<TaskComment> getTaskComment() {
        if (taskComment == null) {
            taskComment = new ArrayList<TaskComment>();
        }
        return this.taskComment;
    }

    /**
     * Gets the value of the artifacts property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the artifacts property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getArtifacts().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TaskArtifacts }
     * 
     * 
     */
    public List<TaskArtifacts> getArtifacts() {
        if (artifacts == null) {
            artifacts = new ArrayList<TaskArtifacts>();
        }
        return this.artifacts;
    }

    /**
     * Gets the value of the assignmentDetails property.
     * 
     * @return
     *     possible object is
     *     {@link TaskAssignementDetails }
     *     
     */
    public TaskAssignementDetails getAssignmentDetails() {
        return assignmentDetails;
    }

    /**
     * Sets the value of the assignmentDetails property.
     * 
     * @param value
     *     allowed object is
     *     {@link TaskAssignementDetails }
     *     
     */
    public void setAssignmentDetails(TaskAssignementDetails value) {
        this.assignmentDetails = value;
    }

    /**
     * Gets the value of the subTaskList property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the subTaskList property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSubTaskList().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Task }
     * 
     * 
     */
    public List<Task> getSubTaskList() {
        if (subTaskList == null) {
            subTaskList = new ArrayList<Task>();
        }
        return this.subTaskList;
    }

    /**
     * Gets the value of the taskStatus property.
     * 
     * @return
     *     possible object is
     *     {@link TaskStatus }
     *     
     */
    public TaskStatus getTaskStatus() {
        return taskStatus;
    }

    /**
     * Sets the value of the taskStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link TaskStatus }
     *     
     */
    public void setTaskStatus(TaskStatus value) {
        this.taskStatus = value;
    }

    /**
     * Gets the value of the notes property.
     * 
     * @return
     *     possible object is
     *     {@link TaskComment }
     *     
     */
    public TaskComment getNotes() {
        return notes;
    }

    /**
     * Sets the value of the notes property.
     * 
     * @param value
     *     allowed object is
     *     {@link TaskComment }
     *     
     */
    public void setNotes(TaskComment value) {
        this.notes = value;
    }

}
