//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-520 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.08.14 at 04:03:17 PM IST 
//

package pcs.pradeep.dubey.com.customer;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;

import pcs.pradeep.dubey.com.baseentity.AddressDetails;
import pcs.pradeep.dubey.com.baseentity.CommunicationDetails;
import pcs.pradeep.dubey.com.baseentity.PersonalDetails;

/**
 * <p>
 * Java class for Employee complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name="Employee">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="customerId" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="personalDetails" type="{http:/com.dubey.pradeep.pcs/baseEntity}PersonalDetails"/>
 *         &lt;element name="communicationDetails" type="{http:/com.dubey.pradeep.pcs/baseEntity}CommunicationDetails"/>
 *         &lt;element name="addressDetails" type="{http:/com.dubey.pradeep.pcs/baseEntity}AddressDetails"/>
 *         &lt;element name="creationDate" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlRootElement(name = "Customer")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Customer", propOrder = { "customerId", "personalDetails", "communicationDetails", "addressDetails",
	"creationDate" })
public class Customer {

    @XmlElement(required = true)
    protected String customerId;
    @XmlElement(required = true)
    protected PersonalDetails personalDetails;
    @XmlElement(required = true)
    protected CommunicationDetails communicationDetails;
    @XmlElement(required = true)
    protected AddressDetails addressDetails;
    @XmlElement(required = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar creationDate;

    /**
     * Gets the value of the customerId property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getCustomerId() {
	return customerId;
    }

    /**
     * Sets the value of the customerId property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setCustomerId(String value) {
	this.customerId = value;
    }

    /**
     * Gets the value of the personalDetails property.
     * 
     * @return possible object is {@link PersonalDetails }
     * 
     */
    public PersonalDetails getPersonalDetails() {
	return personalDetails;
    }

    /**
     * Sets the value of the personalDetails property.
     * 
     * @param value
     *            allowed object is {@link PersonalDetails }
     * 
     */
    public void setPersonalDetails(PersonalDetails value) {
	this.personalDetails = value;
    }

    /**
     * Gets the value of the communicationDetails property.
     * 
     * @return possible object is {@link CommunicationDetails }
     * 
     */
    public CommunicationDetails getCommunicationDetails() {
	return communicationDetails;
    }

    /**
     * Sets the value of the communicationDetails property.
     * 
     * @param value
     *            allowed object is {@link CommunicationDetails }
     * 
     */
    public void setCommunicationDetails(CommunicationDetails value) {
	this.communicationDetails = value;
    }

    /**
     * Gets the value of the addressDetails property.
     * 
     * @return possible object is {@link AddressDetails }
     * 
     */
    public AddressDetails getAddressDetails() {
	return addressDetails;
    }

    /**
     * Sets the value of the addressDetails property.
     * 
     * @param value
     *            allowed object is {@link AddressDetails }
     * 
     */
    public void setAddressDetails(AddressDetails value) {
	this.addressDetails = value;
    }

    /**
     * Gets the value of the creationDate property.
     * 
     * @return possible object is {@link XMLGregorianCalendar }
     * 
     */
    public XMLGregorianCalendar getCreationDate() {
	return creationDate;
    }

    /**
     * Sets the value of the creationDate property.
     * 
     * @param value
     *            allowed object is {@link XMLGregorianCalendar }
     * 
     */
    public void setCreationDate(XMLGregorianCalendar value) {
	this.creationDate = value;
    }

}
